export function getTestData() {
  return [
    {
      facilityType: 'FIF',
      grossSalesLedger: '104284.19',
      facilityLimit: '130000',
      approvedSalesLedger: '61212.34',
      clientReference: 1,
      clientName: 'Reckless Peach Timberwolves',
      currentBalance: '66090.518',
    },
    {
      facilityType: 'SIF',
      grossSalesLedger: '74482.36',
      facilityLimit: '90000',
      approvedSalesLedger: null,
      clientReference: 2,
      clientName: 'Righteous Tomato Thunder',
      currentBalance: '44281.0135',
    },
    {
      facilityType: 'SIF',
      grossSalesLedger: '9882',
      facilityLimit: null,
      approvedSalesLedger: null,
      clientReference: 3,
      clientName: 'Best Khaki Jazz',
      currentBalance: null,
    },
    {
      facilityType: 'SIF',
      grossSalesLedger: '3446.64',
      facilityLimit: '5000',
      approvedSalesLedger: null,
      clientReference: 4,
      clientName: 'National Black Wildcats',
      currentBalance: '0',
    },
    {
      facilityType: 'FIF',
      grossSalesLedger: '99128.62',
      facilityLimit: '80000',
      approvedSalesLedger: '64708.31',
      clientReference: 5,
      clientName: 'Top Gold Falcons',
      currentBalance: '39650.446',
    },
    {
      facilityType: 'FIF',
      grossSalesLedger: '11776.39',
      facilityLimit: '10000',
      approvedSalesLedger: '6597.87',
      clientReference: 6,
      clientName: 'Simple Steel Colts',
      currentBalance: '1419.36',
    },
    {
      facilityType: 'FIF',
      grossSalesLedger: '17528.35',
      facilityLimit: '10000',
      approvedSalesLedger: '9681.09',
      clientReference: 7,
      clientName: 'Large Ivory Tigers',
      currentBalance: '2874.3045',
    },
    {
      facilityType: 'SIF',
      grossSalesLedger: '12006.07',
      facilityLimit: null,
      approvedSalesLedger: null,
      clientReference: 8,
      clientName: 'Scary Coral Heat',
      currentBalance: null,
    },
    {
      facilityType: 'SIF',
      grossSalesLedger: '19104',
      facilityLimit: null,
      approvedSalesLedger: null,
      clientReference: 9,
      clientName: 'Simple Gold Tigers',
      currentBalance: null,
    },
    {
      facilityType: 'FIF',
      grossSalesLedger: '8561.25',
      facilityLimit: '10000',
      approvedSalesLedger: '5357.83',
      clientReference: 10,
      clientName: 'Simple Yellow Kings',
      currentBalance: '3986.8035',
    },
    {
      facilityType: 'FIF',
      grossSalesLedger: '100396.64',
      facilityLimit: '80000',
      approvedSalesLedger: '44713.95',
      clientReference: 11,
      clientName: 'Creative Blue Jets',
      currentBalance: '6687.6',
    },
    {
      facilityType: 'FIF',
      grossSalesLedger: '145137.08',
      facilityLimit: '70000',
      approvedSalesLedger: '70000',
      clientReference: 12,
      clientName: 'Top Peach Doctors',
      currentBalance: '32294.861',
    },
    {
      facilityType: 'SIF',
      grossSalesLedger: '161751.36',
      facilityLimit: '210000',
      approvedSalesLedger: null,
      clientReference: 13,
      clientName: 'Slow Tomato Ravens',
      currentBalance: '105780.4855',
    },
    {
      facilityType: 'FIF',
      grossSalesLedger: '37017.55',
      facilityLimit: '20000',
      approvedSalesLedger: '20000',
      clientReference: 14,
      clientName: 'Wise Gold Rockets',
      currentBalance: '4052.8745',
    },
    {
      facilityType: 'SIF',
      grossSalesLedger: '4013.54',
      facilityLimit: null,
      approvedSalesLedger: null,
      clientReference: 15,
      clientName: 'National Yellow Warriors',
      currentBalance: null,
    },
    {
      facilityType: 'FIF',
      grossSalesLedger: '5081.18',
      facilityLimit: '5000',
      approvedSalesLedger: '3251.89',
      clientReference: 16,
      clientName: 'Reckless Red Cardinals',
      currentBalance: '1422.604',
    },
    {
      facilityType: 'FIF',
      grossSalesLedger: '322309.43',
      facilityLimit: '270000',
      approvedSalesLedger: '227772.25',
      clientReference: 17,
      clientName: 'Reckless Azure Bengals',
      currentBalance: '133235.064',
    },
    {
      facilityType: 'FIF',
      grossSalesLedger: '46658.03',
      facilityLimit: '20000',
      approvedSalesLedger: '20000',
      clientReference: 18,
      clientName: 'Top Aquamarine Raiders',
      currentBalance: '6873.78',
    },
    {
      facilityType: 'SIF',
      grossSalesLedger: '5246',
      facilityLimit: '5000',
      approvedSalesLedger: null,
      clientReference: 19,
      clientName: 'Best Peach Heat',
      currentBalance: '0',
    },
  ];
}
